// Auto-generated by scripts/scan-component-status.js — do not edit by hand.
// Regenerate: GH_SCAN_TOKEN=$(gh auth token) node scripts/scan-component-status.js
// Rows come from the documented component names in ComponentGallery/data.ts;
// symbols are scanned from the Android, iOS and Web source repos.

export type VariantGroup = { group: string; values: string[] };
export type CodeSymbol = { symbol: string; variants?: VariantGroup[] };

export type ComponentStatusRow = {
  id: string;
  displayName: string;
  androidCommonUi: CodeSymbol[];
  androidCompose: CodeSymbol[];
  ios: CodeSymbol[];
  web: CodeSymbol[];
};

export type ComponentStatusCategory = {
  label: string;
  rows: ComponentStatusRow[];
};

export type UnmatchedSymbol = {
  platform: string;
  symbol: string;
  sourcePath: string;
};

export const componentStatusCategories: ComponentStatusCategory[] = [
  {
    "label": "Assets",
    "rows": [
      {
        "id": "animations",
        "displayName": "Animations",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.AnimationView"
          }
        ],
        "web": []
      },
      {
        "id": "graphic-blocks",
        "displayName": "Graphic blocks",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.GraphicBlock",
            "variants": [
              {
                "group": "Size",
                "values": [
                  "small",
                  "medium",
                  "large"
                ]
              }
            ]
          }
        ],
        "web": []
      },
      {
        "id": "icons",
        "displayName": "Icons",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.Icon",
            "variants": [
              {
                "group": "IconSize",
                "values": [
                  "extraSmall",
                  "small",
                  "large",
                  "extraLarge"
                ]
              }
            ]
          }
        ],
        "web": []
      }
    ]
  },
  {
    "label": "Buttons",
    "rows": [
      {
        "id": "floating-button",
        "displayName": "Floating button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "FloatingButtonBig"
          },
          {
            "symbol": "FloatingButtonDestructiveBig"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "floating-icon-button",
        "displayName": "Floating icon button",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.FloatingIconButton",
            "variants": [
              {
                "group": "ButtonType",
                "values": [
                  "prominent"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "FloatingIconButton",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "prominent"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "icon-button",
        "displayName": "Icon button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "IconButtonMedium"
          },
          {
            "symbol": "IconButtonBig"
          },
          {
            "symbol": "CircleOutlinedIconButtonBig"
          }
        ],
        "ios": [
          {
            "symbol": "DS.IconButton",
            "variants": [
              {
                "group": "IconButtonType",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "IconButtonSize",
                "values": [
                  "big",
                  "medium"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "IconButton",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "size",
                "values": [
                  "medium",
                  "large"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "primary-button",
        "displayName": "Primary button",
        "androidCommonUi": [
          {
            "symbol": "ThrottledButton"
          }
        ],
        "androidCompose": [
          {
            "symbol": "ButtonPrimaryBig"
          },
          {
            "symbol": "ButtonPrimaryBigWithCountDown"
          },
          {
            "symbol": "ButtonPrimaryDestructiveBig"
          },
          {
            "symbol": "ButtonPrimarySmall"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Button",
            "variants": [
              {
                "group": "Size",
                "values": [
                  "small",
                  "big"
                ]
              },
              {
                "group": "Style",
                "values": [
                  "primary",
                  "secondary",
                  "secondaryInverted",
                  "tertiary"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "Button",
            "variants": [
              {
                "group": "size",
                "values": [
                  "small",
                  "large"
                ]
              },
              {
                "group": "variant",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "color",
                "values": [
                  "default",
                  "destructive"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "secondary-button",
        "displayName": "Secondary button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ButtonSecondaryBig"
          },
          {
            "symbol": "ButtonSecondaryBigInverse"
          },
          {
            "symbol": "ButtonSecondarySmall"
          },
          {
            "symbol": "ButtonSecondarySmallInverse"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Button",
            "variants": [
              {
                "group": "Size",
                "values": [
                  "small",
                  "big"
                ]
              },
              {
                "group": "Style",
                "values": [
                  "primary",
                  "secondary",
                  "secondaryInverted",
                  "tertiary"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "Button",
            "variants": [
              {
                "group": "size",
                "values": [
                  "small",
                  "large"
                ]
              },
              {
                "group": "variant",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "color",
                "values": [
                  "default",
                  "destructive"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "tertiary-button",
        "displayName": "Tertiary button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ButtonTertiary"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Button",
            "variants": [
              {
                "group": "Size",
                "values": [
                  "small",
                  "big"
                ]
              },
              {
                "group": "Style",
                "values": [
                  "primary",
                  "secondary",
                  "secondaryInverted",
                  "tertiary"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "Button",
            "variants": [
              {
                "group": "size",
                "values": [
                  "small",
                  "large"
                ]
              },
              {
                "group": "variant",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "color",
                "values": [
                  "default",
                  "destructive"
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "label": "Content display and Lists",
    "rows": [
      {
        "id": "expandable-list",
        "displayName": "Expandable list",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "leading-list",
        "displayName": "Leading list",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      }
    ]
  },
  {
    "label": "Feedback",
    "rows": [
      {
        "id": "badge",
        "displayName": "Badge",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "BadgedBox"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Badge"
          }
        ],
        "web": [
          {
            "symbol": "Badge"
          }
        ]
      },
      {
        "id": "message-bar",
        "displayName": "Message bar",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "MessageBarNeutral"
          },
          {
            "symbol": "MessageBarAlert"
          },
          {
            "symbol": "MessageBarError"
          },
          {
            "symbol": "MessageBarStack"
          },
          {
            "symbol": "BannerMessageNeutral"
          },
          {
            "symbol": "BannerMessageAlert"
          },
          {
            "symbol": "BannerMessageSuccess"
          },
          {
            "symbol": "BannerMessageError"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "MessageBar",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "neutral",
                  "success",
                  "error",
                  "alert"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "message-box",
        "displayName": "Message box",
        "androidCommonUi": [
          {
            "symbol": "OverlayDialog"
          }
        ],
        "androidCompose": [
          {
            "symbol": "MessagePopUp"
          },
          {
            "symbol": "MessageDialogContent"
          }
        ],
        "ios": [
          {
            "symbol": "DS.MessageBoxView",
            "variants": [
              {
                "group": "Style",
                "values": [
                  "neutral"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "MessageBox",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "success",
                  "error",
                  "warning"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "snackbar",
        "displayName": "Snackbar",
        "androidCommonUi": [
          {
            "symbol": "SnackbarView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "RoadrunnerSnackbarHost"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Snackbar"
          }
        ],
        "web": [
          {
            "symbol": "Snackbar",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "success",
                  "error",
                  "alert"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "tag",
        "displayName": "Tag",
        "androidCommonUi": [
          {
            "symbol": "TagFlexboxView"
          },
          {
            "symbol": "TagView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "TagPaleWhite"
          },
          {
            "symbol": "TagPaleSuccess"
          },
          {
            "symbol": "TagPaleError"
          },
          {
            "symbol": "TagPaleAlert"
          },
          {
            "symbol": "TagPaleNeutral"
          },
          {
            "symbol": "TagPaleActive"
          },
          {
            "symbol": "TagBoldNeutral"
          },
          {
            "symbol": "TagBoldSuccess"
          },
          {
            "symbol": "TagBoldError"
          },
          {
            "symbol": "TagBoldTransparent"
          },
          {
            "symbol": "TagBoldAlert"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Tag"
          }
        ],
        "web": [
          {
            "symbol": "Tag",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "pale",
                  "bold"
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "label": "Form",
    "rows": [
      {
        "id": "checkbox",
        "displayName": "Checkbox",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "CheckboxBig"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Checkbox"
          }
        ],
        "web": [
          {
            "symbol": "Checkbox"
          }
        ]
      },
      {
        "id": "chips",
        "displayName": "Chips",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "Chip"
          },
          {
            "symbol": "ChipRemovable"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Chip"
          }
        ],
        "web": [
          {
            "symbol": "Chip"
          }
        ]
      },
      {
        "id": "drop-down",
        "displayName": "Drop Down",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "DropdownBig"
          },
          {
            "symbol": "Dropdown"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Dropdown"
          }
        ],
        "web": [
          {
            "symbol": "Dropdown"
          }
        ]
      },
      {
        "id": "radio-button",
        "displayName": "Radio Button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "RadioButton"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Radio"
          }
        ],
        "web": [
          {
            "symbol": "Radio"
          }
        ]
      },
      {
        "id": "switch",
        "displayName": "Switch",
        "androidCommonUi": [
          {
            "symbol": "ToggleControl"
          },
          {
            "symbol": "ToggleWithLabelsView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "SwitchBig"
          },
          {
            "symbol": "SwitchBigWithText"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Switch"
          }
        ],
        "web": [
          {
            "symbol": "Switch"
          }
        ]
      },
      {
        "id": "text-area",
        "displayName": "Text Area",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "TextAreaFullScreen"
          },
          {
            "symbol": "TextArea"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "TextArea"
          }
        ]
      },
      {
        "id": "text-field",
        "displayName": "Text Field",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "PasswordField"
          },
          {
            "symbol": "TextInputBigV2"
          }
        ],
        "ios": [
          {
            "symbol": "DS.TextInput"
          }
        ],
        "web": [
          {
            "symbol": "TextInput"
          }
        ]
      },
      {
        "id": "tile",
        "displayName": "Tile",
        "androidCommonUi": [
          {
            "symbol": "ExpandedTileView"
          },
          {
            "symbol": "HorizontalTileListView"
          },
          {
            "symbol": "TileView"
          }
        ],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Tile"
          }
        ]
      }
    ]
  },
  {
    "label": "Layout",
    "rows": [
      {
        "id": "empty-screen",
        "displayName": "Empty screen",
        "androidCommonUi": [
          {
            "symbol": "ErrorView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "EmptyScreen"
          },
          {
            "symbol": "ErrorScreen"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "horizontal-divider",
        "displayName": "Horizontal divider",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "DividerHorizontal"
          },
          {
            "symbol": "DividerHorizontalThin"
          },
          {
            "symbol": "DividerHorizontalExtraThick"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Divider",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "thin",
                  "thick",
                  "extra-thick"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "vertical-divider",
        "displayName": "Vertical divider",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "DividerVertical"
          },
          {
            "symbol": "DividerVerticalThin"
          },
          {
            "symbol": "DividerVerticalMedium"
          },
          {
            "symbol": "DividerVerticalThick"
          },
          {
            "symbol": "DividerVerticalDashed"
          },
          {
            "symbol": "VerticalDivider"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Divider",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "thin",
                  "thick",
                  "extra-thick"
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "label": "Loaders",
    "rows": [
      {
        "id": "skeleton-screen",
        "displayName": "Skeleton screen",
        "androidCommonUi": [
          {
            "symbol": "SkeletonView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "SkeletonRowBig"
          },
          {
            "symbol": "SkeletonSquareBig"
          },
          {
            "symbol": "SkeletonRowMedium"
          },
          {
            "symbol": "SkeletonSquareMedium"
          },
          {
            "symbol": "SkeletonRowSmall"
          },
          {
            "symbol": "SkeletonSquareSmall"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Skeleton",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "bar",
                  "square"
                ]
              },
              {
                "group": "size",
                "values": [
                  "small",
                  "medium",
                  "large"
                ]
              },
              {
                "group": "color",
                "values": [
                  "light",
                  "dark"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "skeleton",
        "displayName": "Skeleton",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Skeleton",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "bar",
                  "square"
                ]
              },
              {
                "group": "size",
                "values": [
                  "small",
                  "medium",
                  "large"
                ]
              },
              {
                "group": "color",
                "values": [
                  "light",
                  "dark"
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "label": "Navigation",
    "rows": [
      {
        "id": "content-header",
        "displayName": "Content header",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ContentHeaderDefault"
          },
          {
            "symbol": "ContentHeaderWithSuffix"
          },
          {
            "symbol": "ContentHeaderCentered"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "ContentHeader"
          }
        ]
      },
      {
        "id": "header",
        "displayName": "Header",
        "androidCommonUi": [
          {
            "symbol": "HeaderView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "Header"
          },
          {
            "symbol": "ElevatedHeader"
          },
          {
            "symbol": "BottomElevatedHeader"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Header",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "elevated"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "tabs",
        "displayName": "Tabs",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ScrollableTabRow"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Tabs"
          }
        ]
      }
    ]
  },
  {
    "label": "Overlay",
    "rows": [
      {
        "id": "action-picker",
        "displayName": "Action picker",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "bottom-sheet",
        "displayName": "Bottom sheet",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.BottomSheetView"
          }
        ],
        "web": [
          {
            "symbol": "BottomSheet"
          }
        ]
      },
      {
        "id": "date-picker",
        "displayName": "Date picker",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "DatePicker"
          }
        ]
      },
      {
        "id": "option-picker",
        "displayName": "Option picker",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "time-picker",
        "displayName": "Time picker",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      }
    ]
  },
  {
    "label": "Progressors and Charts",
    "rows": [
      {
        "id": "circle-chart",
        "displayName": "Circle Chart",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ProgressorCircleDefault"
          },
          {
            "symbol": "ProgressorCircleSuccess"
          },
          {
            "symbol": "ProgressorCircleAlert"
          },
          {
            "symbol": "ProgressorCircleError"
          },
          {
            "symbol": "ProgressorCircleNeutral"
          }
        ],
        "ios": [
          {
            "symbol": "DS.DonutIndicator"
          },
          {
            "symbol": "DS.Circle"
          }
        ],
        "web": []
      },
      {
        "id": "pie-chart",
        "displayName": "Pie Chart",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.Pie"
          }
        ],
        "web": []
      },
      {
        "id": "sectioned-progress-bar",
        "displayName": "Sectioned Progress Bar",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "SectionedProgressBar",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "success",
                  "error",
                  "alert",
                  "neutral"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "specs-bar-chart",
        "displayName": "Specs Bar Chart",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "stepper",
        "displayName": "Stepper",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.StepperView"
          }
        ],
        "web": [
          {
            "symbol": "Stepper"
          }
        ]
      }
    ]
  }
];

/** Flat view of every row, for totals and lookups. */
export const componentStatusRows: ComponentStatusRow[] =
  componentStatusCategories.flatMap((category) => category.rows);

export const unmatchedSymbols: UnmatchedSymbol[] = [
  {
    "platform": "Android – common-ui",
    "symbol": "InlineMessage",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/InlineMessage.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "LoadingDialogFullScreen",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/LoadingDialogFullScreen.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "PillWrapView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/PillWrapView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "PullToRefreshLayout",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/PullToRefreshLayout.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "RoadrunnerCardView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/RoadrunnerCardView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "CalendarCellDayView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/calendar/CalendarCellDayView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "CalendarView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/calendar/CalendarView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "CalendarWeekDaysView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/calendar/CalendarWeekDaysView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "ChooseOptionFragment",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/chooseoption/ChooseOptionFragment.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "FullWidthMultiRowListItemView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/list/item/FullWidthMultiRowListItemView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "FullWidthSingleRowListItemView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/list/item/FullWidthSingleRowListItemView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "SummationView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/summation/SummationView.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "LinkBig",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/actions/links/Link.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "LinkMedium",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/actions/links/Link.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "LinkSmall",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/actions/links/Link.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "LinkifyPhoneNumberText",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/actions/links/LinkifyText.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "LinkifyPhoneNumberAndUrlText",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/actions/links/LinkifyText.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "LinkifyPlaceholder",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/actions/links/LinkifyText.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "OverFlowLinkifyPhoneNumberText",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/actions/links/LinkifyText.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "SliderButton",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/buttons/slider/SliderButton.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "SliderButtonWithCountDown",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/buttons/slider/SliderButton.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "SliderHandle",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/buttons/slider/SliderButtonContainer.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "PhonePrefixCard",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/forms/PhonePrefixCard.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "ToggleCell",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/forms/Toggle.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "ToggleBig",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/forms/Toggle.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "LoadingFullScreen",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/forms/pattern/LoadingFullScreen.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "PullToRefresh",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/indicators/loading/PullToRefresh.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "SmallSectionedCircleProgressorDefault",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/indicators/progress/SectionedCircleProgressor.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "BigSectionedCircleProgressorDefault",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/indicators/progress/SectionedCircleProgressor.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "ShimmeringDots",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/indicators/shimmer/ShimmeringDots.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "ShimmeringHorizontalBar",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/indicators/shimmer/ShimmeringHorizontalBar.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "ShimmeringText",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/indicators/shimmer/ShimmeringText.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "MessageInlineSuccess",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/message/InlineMessage.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "MessageInlineAlert",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/message/InlineMessage.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "MessageInlineError",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/message/InlineMessage.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "PasswordRuleContent",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/message/password/PasswordRuleContent.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "PinDigitDisplay",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/pin/PinDigitDisplay.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "PinValidationRow",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/pin/PinValidationRow.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "TaskStatusIndicator",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/stepper/TaskStatusIndicator.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "CircleWithNumber",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/stepper/TaskStatusIndicator.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "CircleWithTicks",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/stepper/TaskStatusIndicator.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "CircleWithContent",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/stepper/TaskStatusIndicator.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "Tooltip",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/tooltip/Tooltip.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "TooltipPopup",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/tooltip/Tooltip.kt"
  },
  {
    "platform": "Android – rrds-compose",
    "symbol": "TooltipContent",
    "sourcePath": "rrds-compose/src/main/java/com/roadrunner/rrds/compose/component/tooltip/Tooltip.kt"
  },
  {
    "platform": "iOS",
    "symbol": "DS.AutomaticButton",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/AutomaticButton/AutomaticButton.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.BubbleComponent",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/Bubble/BubbleComponent.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.GraphicMessage",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/Cards/GraphicMessage/GraphicMessage.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.DialogView",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/Dialog/DialogView.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.ParagraphView",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/ParagraphView/ParagraphView.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.RadioGroup",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/Radio/RadioGroup.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.TextWithLinks",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/TextWithLinks/TextWithLinks.swift"
  },
  {
    "platform": "Web",
    "symbol": "Accordion",
    "sourcePath": "packages/core/src/components/accordion/"
  },
  {
    "platform": "Web",
    "symbol": "ActionCard",
    "sourcePath": "packages/core/src/components/action-card/"
  },
  {
    "platform": "Web",
    "symbol": "Card",
    "sourcePath": "packages/core/src/components/card/"
  },
  {
    "platform": "Web",
    "symbol": "Carousel",
    "sourcePath": "packages/core/src/components/carousel/"
  },
  {
    "platform": "Web",
    "symbol": "DatePickerDay",
    "sourcePath": "packages/core/src/components/date-picker/"
  },
  {
    "platform": "Web",
    "symbol": "DatePickerMonth",
    "sourcePath": "packages/core/src/components/date-picker/"
  },
  {
    "platform": "Web",
    "symbol": "Dialog",
    "sourcePath": "packages/core/src/components/dialog/"
  },
  {
    "platform": "Web",
    "symbol": "FullScreenModal",
    "sourcePath": "packages/core/src/components/full-screen-modal/"
  },
  {
    "platform": "Web",
    "symbol": "Image",
    "sourcePath": "packages/core/src/components/image/"
  },
  {
    "platform": "Web",
    "symbol": "ListItem",
    "sourcePath": "packages/core/src/components/list-item/"
  },
  {
    "platform": "Web",
    "symbol": "List",
    "sourcePath": "packages/core/src/components/list/"
  },
  {
    "platform": "Web",
    "symbol": "NumericStepper",
    "sourcePath": "packages/core/src/components/numeric-stepper/"
  },
  {
    "platform": "Web",
    "symbol": "ProgressBar",
    "sourcePath": "packages/core/src/components/progress-bar/"
  },
  {
    "platform": "Web",
    "symbol": "PullToRefresh",
    "sourcePath": "packages/core/src/components/pull-to-refresh/"
  },
  {
    "platform": "Web",
    "symbol": "Spinner",
    "sourcePath": "packages/core/src/components/spinner/"
  },
  {
    "platform": "Web",
    "symbol": "SyncingSpinner",
    "sourcePath": "packages/core/src/components/syncing-spinner/"
  },
  {
    "platform": "Web",
    "symbol": "Tooltip",
    "sourcePath": "packages/core/src/components/tooltip/"
  },
  {
    "platform": "Web",
    "symbol": "UploadedItem",
    "sourcePath": "packages/core/src/components/uploaded-item/"
  },
  {
    "platform": "Web",
    "symbol": "WheelPicker",
    "sourcePath": "packages/core/src/components/wheel-picker/"
  }
];

export const generatedAt = "2026-08-07";
