// Auto-generated by scripts/scan-component-status.js — do not edit by hand.
// Regenerate: GH_SCAN_TOKEN=$(gh auth token) node scripts/scan-component-status.js
// Rows come from the documented component names in ComponentGallery/data.ts;
// symbols are scanned from the Android, iOS and Web source repos.

export type VariantGroup = { group: string; values: string[] };
export type CodeSymbol = { symbol: string; variants?: VariantGroup[] };

export type ComponentStatusRow = {
  id: string;
  displayName: string;
  /** Exists in code but has no docs page yet. */
  undocumented?: boolean;
  androidCommonUi: CodeSymbol[];
  androidCompose: CodeSymbol[];
  ios: CodeSymbol[];
  web: CodeSymbol[];
};

export type ComponentStatusCategory = {
  label: string;
  rows: ComponentStatusRow[];
};

export type UnmatchedSymbol = {
  platform: string;
  symbol: string;
  sourcePath: string;
};

export const componentStatusCategories: ComponentStatusCategory[] = [
  {
    "label": "Assets",
    "rows": [
      {
        "id": "animations",
        "displayName": "Animations",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.AnimationView"
          }
        ],
        "web": []
      },
      {
        "id": "graphic-blocks",
        "displayName": "Graphic blocks",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.GraphicBlock",
            "variants": [
              {
                "group": "Size",
                "values": [
                  "small",
                  "medium",
                  "large"
                ]
              }
            ]
          }
        ],
        "web": []
      },
      {
        "id": "icons",
        "displayName": "Icons",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.Icon",
            "variants": [
              {
                "group": "IconSize",
                "values": [
                  "extraSmall",
                  "small",
                  "large",
                  "extraLarge"
                ]
              }
            ]
          }
        ],
        "web": []
      }
    ]
  },
  {
    "label": "Buttons",
    "rows": [
      {
        "id": "floating-button",
        "displayName": "Floating button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "FloatingButtonBig"
          },
          {
            "symbol": "FloatingButtonDestructiveBig"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "floating-icon-button",
        "displayName": "Floating icon button",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.FloatingIconButton",
            "variants": [
              {
                "group": "ButtonType",
                "values": [
                  "prominent"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "FloatingIconButton",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "prominent"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "icon-button",
        "displayName": "Icon button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "IconButtonMedium"
          },
          {
            "symbol": "IconButtonBig"
          },
          {
            "symbol": "CircleOutlinedIconButtonBig"
          }
        ],
        "ios": [
          {
            "symbol": "DS.IconButton",
            "variants": [
              {
                "group": "IconButtonType",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "IconButtonSize",
                "values": [
                  "big",
                  "medium"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "IconButton",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "size",
                "values": [
                  "medium",
                  "large"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "primary-button",
        "displayName": "Primary button",
        "androidCommonUi": [
          {
            "symbol": "ThrottledButton"
          }
        ],
        "androidCompose": [
          {
            "symbol": "ButtonPrimaryBig"
          },
          {
            "symbol": "ButtonPrimaryBigWithCountDown"
          },
          {
            "symbol": "ButtonPrimaryDestructiveBig"
          },
          {
            "symbol": "ButtonPrimarySmall"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Button",
            "variants": [
              {
                "group": "Size",
                "values": [
                  "small",
                  "big"
                ]
              },
              {
                "group": "Style",
                "values": [
                  "primary",
                  "secondary",
                  "secondaryInverted",
                  "tertiary"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "Button",
            "variants": [
              {
                "group": "size",
                "values": [
                  "small",
                  "large"
                ]
              },
              {
                "group": "variant",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "color",
                "values": [
                  "default",
                  "destructive"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "secondary-button",
        "displayName": "Secondary button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ButtonSecondaryBig"
          },
          {
            "symbol": "ButtonSecondaryBigInverse"
          },
          {
            "symbol": "ButtonSecondarySmall"
          },
          {
            "symbol": "ButtonSecondarySmallInverse"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Button",
            "variants": [
              {
                "group": "Size",
                "values": [
                  "small",
                  "big"
                ]
              },
              {
                "group": "Style",
                "values": [
                  "primary",
                  "secondary",
                  "secondaryInverted",
                  "tertiary"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "Button",
            "variants": [
              {
                "group": "size",
                "values": [
                  "small",
                  "large"
                ]
              },
              {
                "group": "variant",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "color",
                "values": [
                  "default",
                  "destructive"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "tertiary-button",
        "displayName": "Tertiary button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ButtonTertiary"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Button",
            "variants": [
              {
                "group": "Size",
                "values": [
                  "small",
                  "big"
                ]
              },
              {
                "group": "Style",
                "values": [
                  "primary",
                  "secondary",
                  "secondaryInverted",
                  "tertiary"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "Button",
            "variants": [
              {
                "group": "size",
                "values": [
                  "small",
                  "large"
                ]
              },
              {
                "group": "variant",
                "values": [
                  "primary",
                  "secondary",
                  "tertiary"
                ]
              },
              {
                "group": "color",
                "values": [
                  "default",
                  "destructive"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "link",
        "displayName": "Link",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "LinkBig"
          },
          {
            "symbol": "LinkMedium"
          },
          {
            "symbol": "LinkSmall"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "slider-button",
        "displayName": "Slider button",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "SliderButton"
          },
          {
            "symbol": "SliderButtonWithCountDown"
          },
          {
            "symbol": "SliderHandle"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "linkify-text",
        "displayName": "Linkify text",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "LinkifyPhoneNumberText"
          },
          {
            "symbol": "LinkifyPhoneNumberAndUrlText"
          },
          {
            "symbol": "LinkifyPlaceholder"
          },
          {
            "symbol": "OverFlowLinkifyPhoneNumberText"
          }
        ],
        "ios": [],
        "web": []
      }
    ]
  },
  {
    "label": "Content display and Lists",
    "rows": [
      {
        "id": "expandable-list",
        "displayName": "Expandable list",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "leading-list",
        "displayName": "Leading list",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "ListItem"
          }
        ]
      },
      {
        "id": "accordion",
        "displayName": "Accordion",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Accordion"
          }
        ]
      },
      {
        "id": "action-card",
        "displayName": "Action card",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "ActionCard"
          }
        ]
      },
      {
        "id": "image",
        "displayName": "Image",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Image",
            "variants": [
              {
                "group": "size",
                "values": [
                  "small",
                  "medium",
                  "large"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "uploaded-item",
        "displayName": "Uploaded item",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "UploadedItem"
          }
        ]
      },
      {
        "id": "list",
        "displayName": "List",
        "undocumented": true,
        "androidCommonUi": [
          {
            "symbol": "FullWidthMultiRowListItemView"
          },
          {
            "symbol": "FullWidthSingleRowListItemView"
          }
        ],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "List"
          }
        ]
      }
    ]
  },
  {
    "label": "Feedback",
    "rows": [
      {
        "id": "badge",
        "displayName": "Badge",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "BadgedBox"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Badge"
          }
        ],
        "web": [
          {
            "symbol": "Badge"
          }
        ]
      },
      {
        "id": "message-bar",
        "displayName": "Message bar",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "MessageBarNeutral"
          },
          {
            "symbol": "MessageBarAlert"
          },
          {
            "symbol": "MessageBarError"
          },
          {
            "symbol": "MessageBarStack"
          },
          {
            "symbol": "BannerMessageNeutral"
          },
          {
            "symbol": "BannerMessageAlert"
          },
          {
            "symbol": "BannerMessageSuccess"
          },
          {
            "symbol": "BannerMessageError"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "MessageBar",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "neutral",
                  "success",
                  "error",
                  "alert"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "message-box",
        "displayName": "Message box",
        "androidCommonUi": [
          {
            "symbol": "OverlayDialog"
          }
        ],
        "androidCompose": [
          {
            "symbol": "MessagePopUp"
          },
          {
            "symbol": "MessageDialogContent"
          }
        ],
        "ios": [
          {
            "symbol": "DS.MessageBoxView",
            "variants": [
              {
                "group": "Style",
                "values": [
                  "neutral"
                ]
              }
            ]
          }
        ],
        "web": [
          {
            "symbol": "MessageBox",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "success",
                  "error",
                  "warning"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "snackbar",
        "displayName": "Snackbar",
        "androidCommonUi": [
          {
            "symbol": "SnackbarView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "RoadrunnerSnackbarHost"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Snackbar"
          }
        ],
        "web": [
          {
            "symbol": "Snackbar",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "success",
                  "error",
                  "alert"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "tag",
        "displayName": "Tag",
        "androidCommonUi": [
          {
            "symbol": "TagFlexboxView"
          },
          {
            "symbol": "TagView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "TagPaleWhite"
          },
          {
            "symbol": "TagPaleSuccess"
          },
          {
            "symbol": "TagPaleError"
          },
          {
            "symbol": "TagPaleAlert"
          },
          {
            "symbol": "TagPaleNeutral"
          },
          {
            "symbol": "TagPaleActive"
          },
          {
            "symbol": "TagBoldNeutral"
          },
          {
            "symbol": "TagBoldSuccess"
          },
          {
            "symbol": "TagBoldError"
          },
          {
            "symbol": "TagBoldTransparent"
          },
          {
            "symbol": "TagBoldAlert"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Tag"
          }
        ],
        "web": [
          {
            "symbol": "Tag",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "pale",
                  "bold"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "inline-message",
        "displayName": "Inline message",
        "undocumented": true,
        "androidCommonUi": [
          {
            "symbol": "InlineMessage",
            "variants": [
              {
                "group": "InlineMessageType",
                "values": [
                  "Success",
                  "Alert",
                  "Error"
                ]
              }
            ]
          }
        ],
        "androidCompose": [
          {
            "symbol": "MessageInlineSuccess"
          },
          {
            "symbol": "MessageInlineAlert"
          },
          {
            "symbol": "MessageInlineError"
          }
        ],
        "ios": [],
        "web": []
      }
    ]
  },
  {
    "label": "Form",
    "rows": [
      {
        "id": "checkbox",
        "displayName": "Checkbox",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "CheckboxBig"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Checkbox"
          }
        ],
        "web": [
          {
            "symbol": "Checkbox"
          }
        ]
      },
      {
        "id": "chips",
        "displayName": "Chips",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "Chip"
          },
          {
            "symbol": "ChipRemovable"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Chip"
          }
        ],
        "web": [
          {
            "symbol": "Chip"
          }
        ]
      },
      {
        "id": "drop-down",
        "displayName": "Drop Down",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "DropdownBig"
          },
          {
            "symbol": "Dropdown"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Dropdown"
          }
        ],
        "web": [
          {
            "symbol": "Dropdown"
          }
        ]
      },
      {
        "id": "radio-button",
        "displayName": "Radio Button",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "RadioButton"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Radio"
          }
        ],
        "web": [
          {
            "symbol": "Radio"
          }
        ]
      },
      {
        "id": "switch",
        "displayName": "Switch",
        "androidCommonUi": [
          {
            "symbol": "ToggleControl"
          },
          {
            "symbol": "ToggleWithLabelsView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "ToggleCell"
          },
          {
            "symbol": "ToggleBig"
          },
          {
            "symbol": "SwitchBig"
          },
          {
            "symbol": "SwitchBigWithText"
          }
        ],
        "ios": [
          {
            "symbol": "DS.Switch"
          }
        ],
        "web": [
          {
            "symbol": "Switch"
          }
        ]
      },
      {
        "id": "text-area",
        "displayName": "Text Area",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "TextAreaFullScreen"
          },
          {
            "symbol": "TextArea"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "TextArea"
          }
        ]
      },
      {
        "id": "text-field",
        "displayName": "Text Field",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "PasswordField"
          },
          {
            "symbol": "TextInputBigV2"
          }
        ],
        "ios": [
          {
            "symbol": "DS.TextInput"
          }
        ],
        "web": [
          {
            "symbol": "TextInput"
          }
        ]
      },
      {
        "id": "tile",
        "displayName": "Tile",
        "androidCommonUi": [
          {
            "symbol": "ExpandedTileView"
          },
          {
            "symbol": "HorizontalTileListView"
          },
          {
            "symbol": "TileView"
          }
        ],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Tile"
          }
        ]
      },
      {
        "id": "numeric-stepper",
        "displayName": "Numeric stepper",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "NumericStepper"
          }
        ]
      },
      {
        "id": "wheel-picker",
        "displayName": "Wheel picker",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "WheelPicker"
          }
        ]
      },
      {
        "id": "pin-entry",
        "displayName": "PIN entry",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "PinDigitDisplay"
          },
          {
            "symbol": "PinValidationRow"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "phone-prefix-card",
        "displayName": "Phone prefix card",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "PhonePrefixCard"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "password-rules",
        "displayName": "Password rules",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "PasswordRuleContent"
          }
        ],
        "ios": [],
        "web": []
      }
    ]
  },
  {
    "label": "Layout",
    "rows": [
      {
        "id": "empty-screen",
        "displayName": "Empty screen",
        "androidCommonUi": [
          {
            "symbol": "ErrorView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "EmptyScreen"
          },
          {
            "symbol": "ErrorScreen"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "horizontal-divider",
        "displayName": "Horizontal divider",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "DividerHorizontal"
          },
          {
            "symbol": "DividerHorizontalThin"
          },
          {
            "symbol": "DividerHorizontalExtraThick"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Divider",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "thin",
                  "thick",
                  "extra-thick"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "vertical-divider",
        "displayName": "Vertical divider",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "DividerVertical"
          },
          {
            "symbol": "DividerVerticalThin"
          },
          {
            "symbol": "DividerVerticalMedium"
          },
          {
            "symbol": "DividerVerticalThick"
          },
          {
            "symbol": "DividerVerticalDashed"
          },
          {
            "symbol": "VerticalDivider"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Divider",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "thin",
                  "thick",
                  "extra-thick"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "card",
        "displayName": "Card",
        "undocumented": true,
        "androidCommonUi": [
          {
            "symbol": "RoadrunnerCardView"
          }
        ],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Card",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "elevated",
                  "alternative"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "carousel",
        "displayName": "Carousel",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Carousel"
          }
        ]
      }
    ]
  },
  {
    "label": "Loaders",
    "rows": [
      {
        "id": "skeleton-screen",
        "displayName": "Skeleton screen",
        "androidCommonUi": [
          {
            "symbol": "SkeletonView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "SkeletonRowBig"
          },
          {
            "symbol": "SkeletonSquareBig"
          },
          {
            "symbol": "SkeletonRowMedium"
          },
          {
            "symbol": "SkeletonSquareMedium"
          },
          {
            "symbol": "SkeletonRowSmall"
          },
          {
            "symbol": "SkeletonSquareSmall"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Skeleton",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "bar",
                  "square"
                ]
              },
              {
                "group": "size",
                "values": [
                  "small",
                  "medium",
                  "large"
                ]
              },
              {
                "group": "color",
                "values": [
                  "light",
                  "dark"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "skeleton",
        "displayName": "Skeleton",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Skeleton",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "bar",
                  "square"
                ]
              },
              {
                "group": "size",
                "values": [
                  "small",
                  "medium",
                  "large"
                ]
              },
              {
                "group": "color",
                "values": [
                  "light",
                  "dark"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "shimmer",
        "displayName": "Shimmer",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ShimmeringDots"
          },
          {
            "symbol": "ShimmeringHorizontalBar"
          },
          {
            "symbol": "ShimmeringText"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "pull-to-refresh",
        "displayName": "Pull to refresh",
        "undocumented": true,
        "androidCommonUi": [
          {
            "symbol": "PullToRefreshLayout"
          }
        ],
        "androidCompose": [
          {
            "symbol": "PullToRefresh"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "PullToRefresh"
          }
        ]
      },
      {
        "id": "full-screen-loading",
        "displayName": "Full-screen loading",
        "undocumented": true,
        "androidCommonUi": [
          {
            "symbol": "LoadingDialogFullScreen"
          }
        ],
        "androidCompose": [
          {
            "symbol": "LoadingFullScreen"
          }
        ],
        "ios": [],
        "web": []
      },
      {
        "id": "spinner",
        "displayName": "Spinner",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "Spinner",
            "variants": [
              {
                "group": "size",
                "values": [
                  "small",
                  "medium",
                  "large"
                ]
              }
            ]
          },
          {
            "symbol": "SyncingSpinner"
          }
        ]
      }
    ]
  },
  {
    "label": "Navigation",
    "rows": [
      {
        "id": "content-header",
        "displayName": "Content header",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ContentHeaderDefault"
          },
          {
            "symbol": "ContentHeaderWithSuffix"
          },
          {
            "symbol": "ContentHeaderCentered"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "ContentHeader"
          }
        ]
      },
      {
        "id": "header",
        "displayName": "Header",
        "androidCommonUi": [
          {
            "symbol": "HeaderView"
          }
        ],
        "androidCompose": [
          {
            "symbol": "Header"
          },
          {
            "symbol": "ElevatedHeader"
          },
          {
            "symbol": "BottomElevatedHeader"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Header",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "elevated"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "tabs",
        "displayName": "Tabs",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ScrollableTabRow"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Tabs"
          }
        ]
      }
    ]
  },
  {
    "label": "Overlay",
    "rows": [
      {
        "id": "action-picker",
        "displayName": "Action picker",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "bottom-sheet",
        "displayName": "Bottom sheet",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.BottomSheetView"
          }
        ],
        "web": [
          {
            "symbol": "BottomSheet"
          }
        ]
      },
      {
        "id": "date-picker",
        "displayName": "Date picker",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "DatePickerDay"
          },
          {
            "symbol": "DatePickerMonth"
          },
          {
            "symbol": "DatePicker"
          }
        ]
      },
      {
        "id": "option-picker",
        "displayName": "Option picker",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "time-picker",
        "displayName": "Time picker",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "tooltip",
        "displayName": "Tooltip",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "Tooltip"
          },
          {
            "symbol": "TooltipPopup"
          },
          {
            "symbol": "TooltipContent"
          }
        ],
        "ios": [],
        "web": [
          {
            "symbol": "Tooltip",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "light",
                  "dark"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "dialog",
        "displayName": "Dialog",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.DialogView"
          }
        ],
        "web": [
          {
            "symbol": "Dialog"
          }
        ]
      },
      {
        "id": "full-screen-modal",
        "displayName": "Full screen modal",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "FullScreenModal"
          }
        ]
      }
    ]
  },
  {
    "label": "Progressors and Charts",
    "rows": [
      {
        "id": "circle-chart",
        "displayName": "Circle Chart",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "ProgressorCircleDefault"
          },
          {
            "symbol": "ProgressorCircleSuccess"
          },
          {
            "symbol": "ProgressorCircleAlert"
          },
          {
            "symbol": "ProgressorCircleError"
          },
          {
            "symbol": "ProgressorCircleNeutral"
          }
        ],
        "ios": [
          {
            "symbol": "DS.DonutIndicator"
          },
          {
            "symbol": "DS.Circle"
          }
        ],
        "web": []
      },
      {
        "id": "pie-chart",
        "displayName": "Pie Chart",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [
          {
            "symbol": "DS.Pie"
          }
        ],
        "web": []
      },
      {
        "id": "sectioned-progress-bar",
        "displayName": "Sectioned Progress Bar",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "SectionedProgressBar",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "success",
                  "error",
                  "alert",
                  "neutral"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "specs-bar-chart",
        "displayName": "Bar chart",
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": []
      },
      {
        "id": "stepper",
        "displayName": "Stepper",
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "TaskStatusIndicator"
          },
          {
            "symbol": "CircleWithNumber"
          },
          {
            "symbol": "CircleWithTicks"
          },
          {
            "symbol": "CircleWithContent"
          }
        ],
        "ios": [
          {
            "symbol": "DS.StepperView"
          }
        ],
        "web": [
          {
            "symbol": "Stepper"
          }
        ]
      },
      {
        "id": "progress-bar",
        "displayName": "Progress bar",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [],
        "ios": [],
        "web": [
          {
            "symbol": "ProgressBar",
            "variants": [
              {
                "group": "variant",
                "values": [
                  "default",
                  "success",
                  "error",
                  "alert",
                  "neutral"
                ]
              }
            ]
          }
        ]
      },
      {
        "id": "sectioned-circle-progressor",
        "displayName": "Sectioned circle progressor",
        "undocumented": true,
        "androidCommonUi": [],
        "androidCompose": [
          {
            "symbol": "SmallSectionedCircleProgressorDefault"
          },
          {
            "symbol": "BigSectionedCircleProgressorDefault"
          }
        ],
        "ios": [],
        "web": []
      }
    ]
  }
];

/** Flat view of every row, for totals and lookups. */
export const componentStatusRows: ComponentStatusRow[] =
  componentStatusCategories.flatMap((category) => category.rows);

export const unmatchedSymbols: UnmatchedSymbol[] = [
  {
    "platform": "Android – common-ui",
    "symbol": "PillWrapView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/PillWrapView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "CalendarCellDayView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/calendar/CalendarCellDayView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "CalendarView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/calendar/CalendarView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "CalendarWeekDaysView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/calendar/CalendarWeekDaysView.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "ChooseOptionFragment",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/chooseoption/ChooseOptionFragment.kt"
  },
  {
    "platform": "Android – common-ui",
    "symbol": "SummationView",
    "sourcePath": "common-ui/src/main/java/com/ui/common/widget/summation/SummationView.kt"
  },
  {
    "platform": "iOS",
    "symbol": "DS.AutomaticButton",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/AutomaticButton/AutomaticButton.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.BubbleComponent",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/Bubble/BubbleComponent.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.GraphicMessage",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/Cards/GraphicMessage/GraphicMessage.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.ParagraphView",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/ParagraphView/ParagraphView.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.RadioGroup",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/Radio/RadioGroup.swift"
  },
  {
    "platform": "iOS",
    "symbol": "DS.TextWithLinks",
    "sourcePath": "Dependencies/DesignSystem/Sources/Components/TextWithLinks/TextWithLinks.swift"
  }
];

export const generatedAt = "2026-08-10";
