// Auto-generated by scanning docs/components/**/overview.mdx — regenerate if components are added/removed.
export type GalleryItem = { slug: string; title: string; image?: string; href: string };
export type GalleryCategory = { label: string; items: GalleryItem[] };

export const galleryCategories: GalleryCategory[] = [
  {
    "label": "Assets",
    "items": [
      {
        "slug": "animations",
        "title": "Animations",
        "image": "/img/components/animations/animations-overview.png",
        "href": "/components/assets/animations/overview"
      },
      {
        "slug": "graphic-blocks",
        "title": "Graphic blocks",
        "image": "/img/components/graphic-blocks/graphic-blocks-overview.png",
        "href": "/components/assets/graphic-blocks/overview"
      },
      {
        "slug": "icons",
        "title": "Icons",
        "image": "/img/components/icons/icons-overview.png",
        "href": "/components/assets/icons/overview"
      }
    ]
  },
  {
    "label": "Buttons",
    "items": [
      {
        "slug": "floating-button",
        "title": "Floating button",
        "image": "/img/components/fab/fab-overview.png",
        "href": "/components/buttons/floating-button/overview"
      },
      {
        "slug": "floating-icon-button",
        "title": "Floating icon button",
        "image": "/img/components/fab-icon/fab-icon-overview.png",
        "href": "/components/buttons/floating-icon-button/overview"
      },
      {
        "slug": "icon-button",
        "title": "Icon button",
        "image": "/img/components/icon-button/icon-button-overview.png",
        "href": "/components/buttons/icon-button/overview"
      },
      {
        "slug": "primary-button",
        "title": "Primary button",
        "image": "/img/components/primary-button/primary-button-overview.png",
        "href": "/components/buttons/primary-button/overview"
      },
      {
        "slug": "secondary-button",
        "title": "Secondary button",
        "image": "/img/components/secondary-button/secondary-button-overview.png",
        "href": "/components/buttons/secondary-button/overview"
      },
      {
        "slug": "tertiary-button",
        "title": "Tertiary button",
        "image": "/img/components/tertiary-button/tertiary-button-overview.png",
        "href": "/components/buttons/tertiary-button/overview"
      },
      {
        "slug": "destructive-button",
        "title": "Destructive button",
        "href": "/components/buttons/destructive-button/overview"
      },
      {
        "slug": "automatic-button",
        "title": "Automatic button",
        "href": "/components/buttons/automatic-button/overview"
      },
      {
        "slug": "slider-button",
        "title": "Slider button",
        "href": "/components/buttons/slider-button/overview"
      },
      {
        "slug": "text-link",
        "title": "Text link",
        "href": "/components/buttons/text-link/overview"
      }
    ]
  },
  {
    "label": "Content display and Lists",
    "items": [
      {
        "slug": "accordion",
        "title": "Accordion",
        "href": "/components/content-display-and-lists/accordion/overview"
      },
      {
        "slug": "leading-list",
        "title": "Leading list",
        "href": "/components/content-display-and-lists/leading-list/overview"
      },
      {
        "slug": "action-cards",
        "title": "Action cards",
        "href": "/components/content-display-and-lists/action-cards/overview"
      },
      {
        "slug": "simple-list",
        "title": "Simple list",
        "href": "/components/content-display-and-lists/simple-list/overview"
      }
    ]
  },
  {
    "label": "Feedback",
    "items": [
      {
        "slug": "badge",
        "title": "Badge",
        "image": "/img/components/badge/badge-overview.png",
        "href": "/components/feedback/badge/overview"
      },
      {
        "slug": "message-bar",
        "title": "Message bar",
        "image": "/img/components/message-bar/message-bar-overview.png",
        "href": "/components/feedback/message-bar/overview"
      },
      {
        "slug": "message-box",
        "title": "Message box",
        "image": "/img/components/message-box/message-box-overview.png",
        "href": "/components/feedback/message-box/overview"
      },
      {
        "slug": "snackbar",
        "title": "Snackbar",
        "image": "/img/components/snackbar/snackbar-overview.png",
        "href": "/components/feedback/snackbar/overview"
      },
      {
        "slug": "tag",
        "title": "Tag",
        "image": "/img/components/tag/tag-overview.png",
        "href": "/components/feedback/tag/overview"
      }
    ]
  },
  {
    "label": "Form",
    "items": [
      {
        "slug": "checkbox",
        "title": "Checkbox",
        "image": "/img/components/checkbox/checkbox-overview.png",
        "href": "/components/form/checkbox/overview"
      },
      {
        "slug": "chips",
        "title": "Chips",
        "image": "/img/components/chips/chips-overview.png",
        "href": "/components/form/chips/overview"
      },
      {
        "slug": "drop-down",
        "title": "Drop Down",
        "image": "/img/components/drop-down/drop-down-overview.png",
        "href": "/components/form/drop-down/overview"
      },
      {
        "slug": "radio-button",
        "title": "Radio Button",
        "image": "/img/components/radio-button/radio-button-overview.png",
        "href": "/components/form/radio-button/overview"
      },
      {
        "slug": "switch",
        "title": "Switch",
        "image": "/img/components/switch/switch-overview.png",
        "href": "/components/form/switch/overview"
      },
      {
        "slug": "text-area",
        "title": "Text Area",
        "image": "/img/components/text-area/text-area-overview.png",
        "href": "/components/form/text-area/overview"
      },
      {
        "slug": "text-input",
        "title": "Text input",
        "image": "/img/components/text-input/text-input-overview.png",
        "href": "/components/form/text-input/overview"
      },
      {
        "slug": "tile",
        "title": "Tile",
        "image": "/img/components/tile/tile-overview.png",
        "href": "/components/form/tile/overview"
      }
    ]
  },
  {
    "label": "Layout",
    "items": [
      {
        "slug": "empty-screen",
        "title": "Empty screen",
        "image": "/img/components/empty-screen/empty-screen-overview.png",
        "href": "/components/layout/empty-screen/overview"
      },
      {
        "slug": "horizontal-divider",
        "title": "Horizontal divider",
        "image": "/img/components/horizontal-divider/horizontal-divider-overview.png",
        "href": "/components/layout/horizontal-divider/overview"
      },
      {
        "slug": "vertical-divider",
        "title": "Vertical divider",
        "image": "/img/components/vertical-divider/vertical-divider-overview.png",
        "href": "/components/layout/vertical-divider/overview"
      },
      {
        "slug": "card",
        "title": "Card",
        "href": "/components/layout/card/overview"
      },
      {
        "slug": "scrim",
        "title": "Scrim",
        "href": "/components/layout/scrim/overview"
      }
    ]
  },
  {
    "label": "Loaders",
    "items": [
      {
        "slug": "skeleton-screen",
        "title": "Skeleton screen",
        "image": "/img/components/skeleton-screen/skeleton-screen-overview.png",
        "href": "/components/loaders/skeleton-screen/overview"
      },
      {
        "slug": "skeleton",
        "title": "Skeleton",
        "image": "/img/components/skeleton/skeleton-overview.png",
        "href": "/components/loaders/skeleton/overview"
      },
      {
        "slug": "loading-bar",
        "title": "Loading bar",
        "href": "/components/loaders/loading-bar/overview"
      },
      {
        "slug": "loading-screen",
        "title": "Loading screen",
        "href": "/components/loaders/loading-screen/overview"
      },
      {
        "slug": "pull-to-refresh",
        "title": "Pull to refresh",
        "href": "/components/loaders/pull-to-refresh/overview"
      }
    ]
  },
  {
    "label": "Navigation",
    "items": [
      {
        "slug": "content-header",
        "title": "Content header",
        "image": "/img/components/content-header/content-header-overview.png",
        "href": "/components/navigation/content-header/overview"
      },
      {
        "slug": "header",
        "title": "Header",
        "image": "/img/components/header/header-overview.png",
        "href": "/components/navigation/header/overview"
      },
      {
        "slug": "tabs",
        "title": "Tabs",
        "image": "/img/components/tabs/tabs-overview.png",
        "href": "/components/navigation/tabs/overview"
      }
    ]
  },
  {
    "label": "Overlay",
    "items": [
      {
        "slug": "action-picker",
        "title": "Action picker",
        "image": "/img/components/action-picker/action-picker-overview.png",
        "href": "/components/overlay/action-picker/overview"
      },
      {
        "slug": "bottom-sheet",
        "title": "Bottom sheet",
        "image": "/img/components/bottom-sheet/bottom-sheet-overview.png",
        "href": "/components/overlay/bottom-sheet/overview"
      },
      {
        "slug": "date-picker",
        "title": "Date picker",
        "image": "/img/components/date-picker/date-picker-overview.png",
        "href": "/components/overlay/date-picker/overview"
      },
      {
        "slug": "option-picker",
        "title": "Option picker",
        "image": "/img/components/option-picker/option-picker-overview.png",
        "href": "/components/overlay/option-picker/overview"
      },
      {
        "slug": "time-picker",
        "title": "Time picker",
        "image": "/img/components/time-picker/time-picker-overview.png",
        "href": "/components/overlay/time-picker/overview"
      }
    ]
  },
  {
    "label": "Progressors and Charts",
    "items": [
      {
        "slug": "circle-chart",
        "title": "Circle Chart",
        "image": "/img/components/circle-chart/circle-chart-overview.png",
        "href": "/components/progressors-and-charts/circle-chart/overview"
      },
      {
        "slug": "pie-chart",
        "title": "Pie Chart",
        "image": "/img/components/pie-chart/pie-chart-overview.png",
        "href": "/components/progressors-and-charts/pie-chart/overview"
      },
      {
        "slug": "sectioned-progress-bar",
        "title": "Sectioned Progress Bar",
        "image": "/img/components/sectioned-progress-bar/sectioned-progress-bar-overview.png",
        "href": "/components/progressors-and-charts/sectioned-progress-bar/overview"
      },
      {
        "slug": "specs-bar-chart",
        "title": "Specs Bar Chart",
        "image": "/img/components/specs-bar-chart/specs-bar-chart-overview.png",
        "href": "/components/progressors-and-charts/specs-bar-chart/overview"
      },
      {
        "slug": "stepper",
        "title": "Stepper",
        "image": "/img/components/stepper/stepper-overview.png",
        "href": "/components/progressors-and-charts/stepper/overview"
      }
    ]
  }
];
