// Placeholder representative icon per component, until a proper icon set is
// designed for this gallery (see PR discussion) — one emoji glyph per
// component slug, purely illustrative.
export const componentIcons: Record<string, string> = {
  animations: '🎬',
  'graphic-blocks': '🖼️',
  icons: '⭐',
  'floating-button': '➕',
  'floating-icon-button': '➕',
  'icon-button': '🔘',
  'primary-button': '🔲',
  'secondary-button': '🔳',
  'tertiary-button': '▫️',
  'destructive-button': '🗑️',
  'automatic-button': '⏱️',
  'slider-button': '👉',
  'text-link': '🔗',
  accordion: '📂',
  'leading-list': '📋',
  'action-cards': '🗂️',
  'simple-list': '📋',
  badge: '🔖',
  'message-bar': '💬',
  'message-box': '📨',
  snackbar: '🍿',
  tag: '🏷️',
  checkbox: '☑️',
  chips: '🔗',
  'drop-down': '🔽',
  'radio-button': '🔘',
  switch: '🎚️',
  'text-area': '📝',
  'text-field': '✏️',
  tile: '🔳',
  'empty-screen': '🗂️',
  'horizontal-divider': '➖',
  'vertical-divider': '➗',
  'skeleton-screen': '💀',
  skeleton: '💀',
  'content-header': '🪧',
  header: '📌',
  tabs: '📑',
  'action-picker': '🎯',
  'bottom-sheet': '🗒️',
  'date-picker': '📅',
  'option-picker': '🧾',
  'time-picker': '⏰',
  'circle-chart': '🟢',
  'pie-chart': '🥧',
  'sectioned-progress-bar': '📶',
  'specs-bar-chart': '📊',
  stepper: '🪜',
};
