import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Two independent sidebars so "Components" and "Guidelines" are separate
// navbar sections. `autogenerated` means the sidebar mirrors the folder
// structure under docs/ — add a new .mdx file and it appears automatically,
// so you rarely touch this file again.

const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    },
  ],
  componentsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'components',
    },
  ],
  guidelinesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guidelines',
    },
  ],
  tokensSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tokens',
    },
  ],
};

export default sidebars;
